//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18408
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOAPServicesTest.RemesasWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Agencia", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class Agencia : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Moneda", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class Moneda : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SimboloField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Simbolo {
            get {
                return this.SimboloField;
            }
            set {
                if ((object.ReferenceEquals(this.SimboloField, value) != true)) {
                    this.SimboloField = value;
                    this.RaisePropertyChanged("Simbolo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Remesa", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class Remesa : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SOAPServicesTest.RemesasWS.Agencia AgenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SOAPServicesTest.RemesasWS.Moneda MonedaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MontoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PINField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SOAPServicesTest.RemesasWS.Agencia Agencia {
            get {
                return this.AgenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.AgenciaField, value) != true)) {
                    this.AgenciaField = value;
                    this.RaisePropertyChanged("Agencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SOAPServicesTest.RemesasWS.Moneda Moneda {
            get {
                return this.MonedaField;
            }
            set {
                if ((object.ReferenceEquals(this.MonedaField, value) != true)) {
                    this.MonedaField = value;
                    this.RaisePropertyChanged("Moneda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Monto {
            get {
                return this.MontoField;
            }
            set {
                if ((this.MontoField.Equals(value) != true)) {
                    this.MontoField = value;
                    this.RaisePropertyChanged("Monto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((this.NumeroField.Equals(value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PIN {
            get {
                return this.PINField;
            }
            set {
                if ((this.PINField.Equals(value) != true)) {
                    this.PINField = value;
                    this.RaisePropertyChanged("PIN");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HoraExcedidaException", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class HoraExcedidaException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetalleErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DetalleError {
            get {
                return this.DetalleErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.DetalleErrorField, value) != true)) {
                    this.DetalleErrorField = value;
                    this.RaisePropertyChanged("DetalleError");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RemesasWS.IRemesas")]
    public interface IRemesas {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemesas/CrearRemesa", ReplyAction="http://tempuri.org/IRemesas/CrearRemesaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SOAPServicesTest.RemesasWS.HoraExcedidaException), Action="http://tempuri.org/IRemesas/CrearRemesaHoraExcedidaExceptionFault", Name="HoraExcedidaException", Namespace="http://schemas.datacontract.org/2004/07/")]
        SOAPServicesTest.RemesasWS.Remesa CrearRemesa(int pin, System.DateTime fecha, SOAPServicesTest.RemesasWS.Agencia agencia, SOAPServicesTest.RemesasWS.Moneda moneda, decimal monto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemesas/CrearRemesa", ReplyAction="http://tempuri.org/IRemesas/CrearRemesaResponse")]
        System.Threading.Tasks.Task<SOAPServicesTest.RemesasWS.Remesa> CrearRemesaAsync(int pin, System.DateTime fecha, SOAPServicesTest.RemesasWS.Agencia agencia, SOAPServicesTest.RemesasWS.Moneda moneda, decimal monto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemesas/ObtenerRemesa", ReplyAction="http://tempuri.org/IRemesas/ObtenerRemesaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SOAPServicesTest.RemesasWS.HoraExcedidaException), Action="http://tempuri.org/IRemesas/ObtenerRemesaHoraExcedidaExceptionFault", Name="HoraExcedidaException", Namespace="http://schemas.datacontract.org/2004/07/")]
        SOAPServicesTest.RemesasWS.Remesa ObtenerRemesa(int numero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemesas/ObtenerRemesa", ReplyAction="http://tempuri.org/IRemesas/ObtenerRemesaResponse")]
        System.Threading.Tasks.Task<SOAPServicesTest.RemesasWS.Remesa> ObtenerRemesaAsync(int numero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemesas/ModificarRemesa", ReplyAction="http://tempuri.org/IRemesas/ModificarRemesaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SOAPServicesTest.RemesasWS.HoraExcedidaException), Action="http://tempuri.org/IRemesas/ModificarRemesaHoraExcedidaExceptionFault", Name="HoraExcedidaException", Namespace="http://schemas.datacontract.org/2004/07/")]
        SOAPServicesTest.RemesasWS.Remesa ModificarRemesa(int numero, int pin, System.DateTime fecha, SOAPServicesTest.RemesasWS.Agencia agencia, SOAPServicesTest.RemesasWS.Moneda moneda, decimal monto, string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemesas/ModificarRemesa", ReplyAction="http://tempuri.org/IRemesas/ModificarRemesaResponse")]
        System.Threading.Tasks.Task<SOAPServicesTest.RemesasWS.Remesa> ModificarRemesaAsync(int numero, int pin, System.DateTime fecha, SOAPServicesTest.RemesasWS.Agencia agencia, SOAPServicesTest.RemesasWS.Moneda moneda, decimal monto, string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemesas/EliminarRemesa", ReplyAction="http://tempuri.org/IRemesas/EliminarRemesaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SOAPServicesTest.RemesasWS.HoraExcedidaException), Action="http://tempuri.org/IRemesas/EliminarRemesaHoraExcedidaExceptionFault", Name="HoraExcedidaException", Namespace="http://schemas.datacontract.org/2004/07/")]
        void EliminarRemesa(int numero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemesas/EliminarRemesa", ReplyAction="http://tempuri.org/IRemesas/EliminarRemesaResponse")]
        System.Threading.Tasks.Task EliminarRemesaAsync(int numero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemesas/ListarRemesas", ReplyAction="http://tempuri.org/IRemesas/ListarRemesasResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SOAPServicesTest.RemesasWS.HoraExcedidaException), Action="http://tempuri.org/IRemesas/ListarRemesasHoraExcedidaExceptionFault", Name="HoraExcedidaException", Namespace="http://schemas.datacontract.org/2004/07/")]
        SOAPServicesTest.RemesasWS.Remesa[] ListarRemesas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemesas/ListarRemesas", ReplyAction="http://tempuri.org/IRemesas/ListarRemesasResponse")]
        System.Threading.Tasks.Task<SOAPServicesTest.RemesasWS.Remesa[]> ListarRemesasAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRemesasChannel : SOAPServicesTest.RemesasWS.IRemesas, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RemesasClient : System.ServiceModel.ClientBase<SOAPServicesTest.RemesasWS.IRemesas>, SOAPServicesTest.RemesasWS.IRemesas {
        
        public RemesasClient() {
        }
        
        public RemesasClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RemesasClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RemesasClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RemesasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SOAPServicesTest.RemesasWS.Remesa CrearRemesa(int pin, System.DateTime fecha, SOAPServicesTest.RemesasWS.Agencia agencia, SOAPServicesTest.RemesasWS.Moneda moneda, decimal monto) {
            return base.Channel.CrearRemesa(pin, fecha, agencia, moneda, monto);
        }
        
        public System.Threading.Tasks.Task<SOAPServicesTest.RemesasWS.Remesa> CrearRemesaAsync(int pin, System.DateTime fecha, SOAPServicesTest.RemesasWS.Agencia agencia, SOAPServicesTest.RemesasWS.Moneda moneda, decimal monto) {
            return base.Channel.CrearRemesaAsync(pin, fecha, agencia, moneda, monto);
        }
        
        public SOAPServicesTest.RemesasWS.Remesa ObtenerRemesa(int numero) {
            return base.Channel.ObtenerRemesa(numero);
        }
        
        public System.Threading.Tasks.Task<SOAPServicesTest.RemesasWS.Remesa> ObtenerRemesaAsync(int numero) {
            return base.Channel.ObtenerRemesaAsync(numero);
        }
        
        public SOAPServicesTest.RemesasWS.Remesa ModificarRemesa(int numero, int pin, System.DateTime fecha, SOAPServicesTest.RemesasWS.Agencia agencia, SOAPServicesTest.RemesasWS.Moneda moneda, decimal monto, string estado) {
            return base.Channel.ModificarRemesa(numero, pin, fecha, agencia, moneda, monto, estado);
        }
        
        public System.Threading.Tasks.Task<SOAPServicesTest.RemesasWS.Remesa> ModificarRemesaAsync(int numero, int pin, System.DateTime fecha, SOAPServicesTest.RemesasWS.Agencia agencia, SOAPServicesTest.RemesasWS.Moneda moneda, decimal monto, string estado) {
            return base.Channel.ModificarRemesaAsync(numero, pin, fecha, agencia, moneda, monto, estado);
        }
        
        public void EliminarRemesa(int numero) {
            base.Channel.EliminarRemesa(numero);
        }
        
        public System.Threading.Tasks.Task EliminarRemesaAsync(int numero) {
            return base.Channel.EliminarRemesaAsync(numero);
        }
        
        public SOAPServicesTest.RemesasWS.Remesa[] ListarRemesas() {
            return base.Channel.ListarRemesas();
        }
        
        public System.Threading.Tasks.Task<SOAPServicesTest.RemesasWS.Remesa[]> ListarRemesasAsync() {
            return base.Channel.ListarRemesasAsync();
        }
    }
}
